using Betting.Core;
using Logging;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.SmartInspect;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Newtonsoft.Json.Linq;
using Placer.Ecambi;
using Placer.Sport888;
using System;
using System.Collections.Generic;
using System.Text;

namespace MyTester
{
    [TestClass]
    public class FivefoldsBetTests
    {
        private BetType betType;
        private double stake;
        private bool ew;
        private BetslipHelper helper;
        private JArray outcomes;
        private ILogger logger;

        [TestInitialize]
        public void Init()
        {
            betType = BetType.Fivefolds;
            stake = 0.01;
            ew = false;
            helper = new BetslipHelper();
            outcomes = InitOutcomes();
            logger = InitLogger();

            logger.LogDebug($"Was generated outcome:\n{outcomes.GetDump()}");
        }
        [TestMethod]
        public void Get_Success_ValidateCoupon_Tests()
        {
            using (logger.BeginScope(LoggerHelper.GetCaller()))
            {
                var toValidateCoupon = helper.CreateCouponToValidate(betType, outcomes, true);

                //logger.LogDebug("Generated to validate coupon:\n" + toValidateCoupon.GetDump());
                //logger.LogDebug("Validate coupon was got from site:\n" + ToValidateCouponBySite["requestCoupon"].GetDump());

                Assert.IsTrue(JToken.DeepEquals(toValidateCoupon, ToValidateCouponBySite["requestCoupon"]));
            }
        }
        [TestMethod]
        public void Get_Success_PlaceBetCoupon_Tests()
        {
            using (logger.BeginScope(LoggerHelper.GetCaller()))
            {
                var placeBet
                    = helper.GenerateCouponToPlaceBet(outcomes, CheckedCouponBySite, betType, stake, ew);

                logger.LogDebug("Validate coupon:\n" + CheckedCouponBySite.GetDump());
                logger.LogDebug("Generated place bet coupon:\n" + placeBet.GetDump());
                logger.LogDebug("Place bet coupon was got from site:\n" + PlaceBetBySite.GetDump());

                Assert.IsTrue(JToken.DeepEquals(placeBet, PlaceBetBySite));
            }
        }

        /**** Data was generated by site ****/
        private JToken ToValidateCouponBySite
        {
            get
            {
                var json = "{\"requestCoupon\":{\"type\":\"RCT_SYSTEM\",\"odds\":[-1,-1,-1,-1,-1,-1],\"outcomeIds\":[[2698667668],[2698667753],[2698667808],[2698667901],[2698667953],[2698667714]],\"selection\":[[],[],[],[],[],[]],\"betsPattern\":\"111111111111111111111111111111111111111111111111111111111111111\",\"isUserLoggedIn\":true}}";
                return JToken.Parse(json);
            }
        }

        private JToken CheckedCouponBySite
        {
            get
            {
                var json = "{\"responseCoupon\":{\"status\":200,\"requestCoupon\":{\"type\":\"RCT_SYSTEM\",\"outcomeIds\":[[2698667668],[2698667753],[2698667808],[2698667901],[2698667953],[2698667714]],\"odds\":[-1,-1,-1,-1,-1,-1],\"betsPattern\":\"111111111111111111111111111111111111111111111111111111111111111\",\"allowOddsChange\":\"AOCT_NO\",\"selection\":[[],[],[],[],[],[]],\"suggestedRetailPunterCategory\":null}}}";
                return JToken.Parse(json)["responseCoupon"]["requestCoupon"];
            }
        }
        private JToken PlaceBetBySite
        {
            get
            {
                var json =
                  "{\"id\":1,\"trackingData\":{\"hasTeaser\":false,\"isBetBuilderCombination\":false,\"selectedOutcomes\":" +
                  "[{\"id\":2698667668,\"outcomeId\":2698667668,\"betofferId\":2198280422,\"eventId\":1006031042,\"oddsApproved\":true,\"approvedEachWayFractionMilli\":250,\"approvedEachWayPlaceLimit\":3,\"eachWayFractionMilli\":250,\"eachWayPlaceLimit\":3,\"eachWayApproved\":true,\"isLiveBetoffer\":false,\"isPrematchBetoffer\":true,\"fromBetBuilder\":false,\"source\":\"Event List View\"}," +
                  "{\"id\":2698667753,\"outcomeId\":2698667753,\"betofferId\":2198280432,\"eventId\":1006031044,\"oddsApproved\":true,\"approvedEachWayFractionMilli\":200,\"approvedEachWayPlaceLimit\":3,\"eachWayFractionMilli\":200,\"eachWayPlaceLimit\":3,\"eachWayApproved\":true,\"isLiveBetoffer\":false,\"isPrematchBetoffer\":true,\"fromBetBuilder\":false,\"source\":\"Event List View\"}," +
                  "{\"id\":2698667808,\"outcomeId\":2698667808,\"betofferId\":2198280437,\"eventId\":1006031045,\"oddsApproved\":true,\"approvedEachWayFractionMilli\":250,\"approvedEachWayPlaceLimit\":3,\"eachWayFractionMilli\":250,\"eachWayPlaceLimit\":3,\"eachWayApproved\":true,\"isLiveBetoffer\":false,\"isPrematchBetoffer\":true,\"fromBetBuilder\":false,\"source\":\"Event List View\"}," +
                  "{\"id\":2698667901,\"outcomeId\":2698667901,\"betofferId\":2198280447,\"eventId\":1006031047,\"oddsApproved\":true,\"approvedEachWayFractionMilli\":250,\"approvedEachWayPlaceLimit\":3,\"eachWayFractionMilli\":250,\"eachWayPlaceLimit\":3,\"eachWayApproved\":true,\"isLiveBetoffer\":false,\"isPrematchBetoffer\":true,\"fromBetBuilder\":false,\"source\":\"Event List View\"}," +
                  "{\"id\":2698667953,\"outcomeId\":2698667953,\"betofferId\":2198280452,\"eventId\":1006031048,\"oddsApproved\":true,\"approvedEachWayFractionMilli\":250,\"approvedEachWayPlaceLimit\":3,\"eachWayFractionMilli\":250,\"eachWayPlaceLimit\":3,\"eachWayApproved\":true,\"isLiveBetoffer\":false,\"isPrematchBetoffer\":true,\"fromBetBuilder\":false,\"source\":\"Event List View\"}," +
                  "{\"id\":2698667714,\"outcomeId\":2698667714,\"betofferId\":2198280427,\"eventId\":1006031043,\"oddsApproved\":true,\"approvedEachWayFractionMilli\":200,\"approvedEachWayPlaceLimit\":3,\"eachWayFractionMilli\":200,\"eachWayPlaceLimit\":3,\"eachWayApproved\":true,\"isLiveBetoffer\":false,\"isPrematchBetoffer\":true,\"fromBetBuilder\":false,\"source\":\"Event List View\"}]}," +
                  "\"requestCoupon\":{\"allowOddsChange\":\"AOCT_NO\",\"odds\":[-1,-1,-1,-1,-1,-1],\"stakes\":[10,10,10,10,10,10],\"outcomeIds\":[[2698667668],[2698667753],[2698667808],[2698667901],[2698667953],[2698667714]],\"type\":\"RCT_SYSTEM\",\"betsPattern\":\"000000000000000000000000000000100000000000000010000000100010110\",\"systemCombinations\":[{\"outcomeIds\":[2698667714],\"outcomePositions\":[6],\"patternIndex\":0},{\"outcomeIds\":[2698667953],\"outcomePositions\":[5],\"patternIndex\":1},{\"outcomeIds\":[2698667714,2698667953],\"outcomePositions\":[6,5],\"patternIndex\":2},{\"outcomeIds\":[2698667901],\"outcomePositions\":[4],\"patternIndex\":3},{\"outcomeIds\":[2698667714,2698667901],\"outcomePositions\":[6,4],\"patternIndex\":4},{\"outcomeIds\":[2698667953,2698667901],\"outcomePositions\":[5,4],\"patternIndex\":5},{\"outcomeIds\":[2698667714,2698667953,2698667901],\"outcomePositions\":[6,5,4],\"patternIndex\":6},{\"outcomeIds\":[2698667808],\"outcomePositions\":[3],\"patternIndex\":7},{\"outcomeIds\":[2698667714,2698667808],\"outcomePositions\":[6,3],\"patternIndex\":8},{\"outcomeIds\":[2698667953,2698667808],\"outcomePositions\":[5,3],\"patternIndex\":9},{\"outcomeIds\":[2698667714,2698667953,2698667808],\"outcomePositions\":[6,5,3],\"patternIndex\":10},{\"outcomeIds\":[2698667901,2698667808],\"outcomePositions\":[4,3],\"patternIndex\":11},{\"outcomeIds\":[2698667714,2698667901,2698667808],\"outcomePositions\":[6,4,3],\"patternIndex\":12},{\"outcomeIds\":[2698667953,2698667901,2698667808],\"outcomePositions\":[5,4,3],\"patternIndex\":13},{\"outcomeIds\":[2698667714,2698667953,2698667901,2698667808],\"outcomePositions\":[6,5,4,3],\"patternIndex\":14},{\"outcomeIds\":[2698667753],\"outcomePositions\":[2],\"patternIndex\":15},{\"outcomeIds\":[2698667714,2698667753],\"outcomePositions\":[6,2],\"patternIndex\":16},{\"outcomeIds\":[2698667953,2698667753],\"outcomePositions\":[5,2],\"patternIndex\":17},{\"outcomeIds\":[2698667714,2698667953,2698667753],\"outcomePositions\":[6,5,2],\"patternIndex\":18},{\"outcomeIds\":[2698667901,2698667753],\"outcomePositions\":[4,2],\"patternIndex\":19},{\"outcomeIds\":[2698667714,2698667901,2698667753],\"outcomePositions\":[6,4,2],\"patternIndex\":20},{\"outcomeIds\":[2698667953,2698667901,2698667753],\"outcomePositions\":[5,4,2],\"patternIndex\":21},{\"outcomeIds\":[2698667714,2698667953,2698667901,2698667753],\"outcomePositions\":[6,5,4,2],\"patternIndex\":22},{\"outcomeIds\":[2698667808,2698667753],\"outcomePositions\":[3,2],\"patternIndex\":23},{\"outcomeIds\":[2698667714,2698667808,2698667753],\"outcomePositions\":[6,3,2],\"patternIndex\":24},{\"outcomeIds\":[2698667953,2698667808,2698667753],\"outcomePositions\":[5,3,2],\"patternIndex\":25},{\"outcomeIds\":[2698667714,2698667953,2698667808,2698667753],\"outcomePositions\":[6,5,3,2],\"patternIndex\":26},{\"outcomeIds\":[2698667901,2698667808,2698667753],\"outcomePositions\":[4,3,2],\"patternIndex\":27},{\"outcomeIds\":[2698667714,2698667901,2698667808,2698667753],\"outcomePositions\":[6,4,3,2],\"patternIndex\":28},{\"outcomeIds\":[2698667953,2698667901,2698667808,2698667753],\"outcomePositions\":[5,4,3,2],\"patternIndex\":29},{\"outcomeIds\":[2698667714,2698667953,2698667901,2698667808,2698667753],\"outcomePositions\":[6,5,4,3,2],\"patternIndex\":30},{\"outcomeIds\":[2698667668],\"outcomePositions\":[1],\"patternIndex\":31},{\"outcomeIds\":[2698667714,2698667668],\"outcomePositions\":[6,1],\"patternIndex\":32},{\"outcomeIds\":[2698667953,2698667668],\"outcomePositions\":[5,1],\"patternIndex\":33},{\"outcomeIds\":[2698667714,2698667953,2698667668],\"outcomePositions\":[6,5,1],\"patternIndex\":34},{\"outcomeIds\":[2698667901,2698667668],\"outcomePositions\":[4,1],\"patternIndex\":35},{\"outcomeIds\":[2698667714,2698667901,2698667668],\"outcomePositions\":[6,4,1],\"patternIndex\":36},{\"outcomeIds\":[2698667953,2698667901,2698667668],\"outcomePositions\":[5,4,1],\"patternIndex\":37},{\"outcomeIds\":[2698667714,2698667953,2698667901,2698667668],\"outcomePositions\":[6,5,4,1],\"patternIndex\":38},{\"outcomeIds\":[2698667808,2698667668],\"outcomePositions\":[3,1],\"patternIndex\":39},{\"outcomeIds\":[2698667714,2698667808,2698667668],\"outcomePositions\":[6,3,1],\"patternIndex\":40},{\"outcomeIds\":[2698667953,2698667808,2698667668],\"outcomePositions\":[5,3,1],\"patternIndex\":41},{\"outcomeIds\":[2698667714,2698667953,2698667808,2698667668],\"outcomePositions\":[6,5,3,1],\"patternIndex\":42},{\"outcomeIds\":[2698667901,2698667808,2698667668],\"outcomePositions\":[4,3,1],\"patternIndex\":43},{\"outcomeIds\":[2698667714,2698667901,2698667808,2698667668],\"outcomePositions\":[6,4,3,1],\"patternIndex\":44},{\"outcomeIds\":[2698667953,2698667901,2698667808,2698667668],\"outcomePositions\":[5,4,3,1],\"patternIndex\":45},{\"outcomeIds\":[2698667714,2698667953,2698667901,2698667808,2698667668],\"outcomePositions\":[6,5,4,3,1],\"patternIndex\":46},{\"outcomeIds\":[2698667753,2698667668],\"outcomePositions\":[2,1],\"patternIndex\":47},{\"outcomeIds\":[2698667714,2698667753,2698667668],\"outcomePositions\":[6,2,1],\"patternIndex\":48},{\"outcomeIds\":[2698667953,2698667753,2698667668],\"outcomePositions\":[5,2,1],\"patternIndex\":49},{\"outcomeIds\":[2698667714,2698667953,2698667753,2698667668],\"outcomePositions\":[6,5,2,1],\"patternIndex\":50},{\"outcomeIds\":[2698667901,2698667753,2698667668],\"outcomePositions\":[4,2,1],\"patternIndex\":51},{\"outcomeIds\":[2698667714,2698667901,2698667753,2698667668],\"outcomePositions\":[6,4,2,1],\"patternIndex\":52},{\"outcomeIds\":[2698667953,2698667901,2698667753,2698667668],\"outcomePositions\":[5,4,2,1],\"patternIndex\":53},{\"outcomeIds\":[2698667714,2698667953,2698667901,2698667753,2698667668],\"outcomePositions\":[6,5,4,2,1],\"patternIndex\":54},{\"outcomeIds\":[2698667808,2698667753,2698667668],\"outcomePositions\":[3,2,1],\"patternIndex\":55},{\"outcomeIds\":[2698667714,2698667808,2698667753,2698667668],\"outcomePositions\":[6,3,2,1],\"patternIndex\":56},{\"outcomeIds\":[2698667953,2698667808,2698667753,2698667668],\"outcomePositions\":[5,3,2,1],\"patternIndex\":57},{\"outcomeIds\":[2698667714,2698667953,2698667808,2698667753,2698667668],\"outcomePositions\":[6,5,3,2,1],\"patternIndex\":58},{\"outcomeIds\":[2698667901,2698667808,2698667753,2698667668],\"outcomePositions\":[4,3,2,1],\"patternIndex\":59},{\"outcomeIds\":[2698667714,2698667901,2698667808,2698667753,2698667668],\"outcomePositions\":[6,4,3,2,1],\"patternIndex\":60},{\"outcomeIds\":[2698667953,2698667901,2698667808,2698667753,2698667668],\"outcomePositions\":[5,4,3,2,1],\"patternIndex\":61},{\"outcomeIds\":[2698667714,2698667953,2698667901,2698667808,2698667753,2698667668],\"outcomePositions\":[6,5,4,3,2,1],\"patternIndex\":62}],\"selection\":[[],[],[],[],[],[]]}}";
                return JToken.Parse(json);
            }
        }
        /****************************************/
        private JArray InitOutcomes()
        {
            // horse and event info
            var json =
                "[{\"id\":2698667668,\"outcomeId\":2698667668,\"betofferId\":2198280422,\"eventId\":1006031042,\"oddsApproved\":true,\"approvedEachWayFractionMilli\":250,\"approvedEachWayPlaceLimit\":3,\"eachWayFractionMilli\":250,\"eachWayPlaceLimit\":3,\"eachWayApproved\":true,\"isLiveBetoffer\":false,\"isPrematchBetoffer\":true,\"fromBetBuilder\":false,\"source\":\"Event List View\"}," +
                "{\"id\":2698667753,\"outcomeId\":2698667753,\"betofferId\":2198280432,\"eventId\":1006031044,\"oddsApproved\":true,\"approvedEachWayFractionMilli\":200,\"approvedEachWayPlaceLimit\":3,\"eachWayFractionMilli\":200,\"eachWayPlaceLimit\":3,\"eachWayApproved\":true,\"isLiveBetoffer\":false,\"isPrematchBetoffer\":true,\"fromBetBuilder\":false,\"source\":\"Event List View\"}," +
                "{\"id\":2698667808,\"outcomeId\":2698667808,\"betofferId\":2198280437,\"eventId\":1006031045,\"oddsApproved\":true,\"approvedEachWayFractionMilli\":250,\"approvedEachWayPlaceLimit\":3,\"eachWayFractionMilli\":250,\"eachWayPlaceLimit\":3,\"eachWayApproved\":true,\"isLiveBetoffer\":false,\"isPrematchBetoffer\":true,\"fromBetBuilder\":false,\"source\":\"Event List View\"}," +
                "{\"id\":2698667901,\"outcomeId\":2698667901,\"betofferId\":2198280447,\"eventId\":1006031047,\"oddsApproved\":true,\"approvedEachWayFractionMilli\":250,\"approvedEachWayPlaceLimit\":3,\"eachWayFractionMilli\":250,\"eachWayPlaceLimit\":3,\"eachWayApproved\":true,\"isLiveBetoffer\":false,\"isPrematchBetoffer\":true,\"fromBetBuilder\":false,\"source\":\"Event List View\"}," +
                "{\"id\":2698667953,\"outcomeId\":2698667953,\"betofferId\":2198280452,\"eventId\":1006031048,\"oddsApproved\":true,\"approvedEachWayFractionMilli\":250,\"approvedEachWayPlaceLimit\":3,\"eachWayFractionMilli\":250,\"eachWayPlaceLimit\":3,\"eachWayApproved\":true,\"isLiveBetoffer\":false,\"isPrematchBetoffer\":true,\"fromBetBuilder\":false,\"source\":\"Event List View\"}," +
                "{\"id\":2698667714,\"outcomeId\":2698667714,\"betofferId\":2198280427,\"eventId\":1006031043,\"oddsApproved\":true,\"approvedEachWayFractionMilli\":200,\"approvedEachWayPlaceLimit\":3,\"eachWayFractionMilli\":200,\"eachWayPlaceLimit\":3,\"eachWayApproved\":true,\"isLiveBetoffer\":false,\"isPrematchBetoffer\":true,\"fromBetBuilder\":false,\"source\":\"Event List View\"}]";
                   
            return JToken.Parse(json) as JArray;
        }

        private ILogger InitLogger()
        {
            AppLogger.LoggerFactory.AddSmartInspect(new SmartInspectConfiguration
            {
                AppName = "Tester",
                Enabled = true,
                Level = LogLevel.Trace,
                DefaultLevel = LogLevel.Trace,
                Connections = @"pipe(reconnect=""true"", reconnect.interval=""5"", async.enabled=""true"", async.throttle=""false"")"
            });
            return AppLogger.CreateLogger("Main");
        }
    }
}
