using Betting.Core;
using Logging;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.SmartInspect;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Newtonsoft.Json.Linq;
using Placer.Ecambi;
using Placer.Sport888;
using System;
using System.Collections.Generic;
using System.Text;

namespace MyTester
{
    [TestClass]
    public class CanadianWinBetTests
    {
        private BetType betType;
        private double stake;
        private bool ew;
        private BetslipHelper helper;
        private JArray outcomes;
        private ILogger logger;

        [TestInitialize]
        public void Init()
        {
            betType = BetType.SuperYankee;
            stake = 0.01;
            ew = true;
            helper = new BetslipHelper();
            outcomes = InitOutcomes();
            logger = InitLogger();

            logger.LogDebug($"Was generated outcome:\n{outcomes.GetDump()}");
        }
        [TestMethod]
        public void Get_Success_ValidateCoupon_Tests()
        {
            using (logger.BeginScope(LoggerHelper.GetCaller()))
            {
                var toValidateCoupon = helper.CreateCouponToValidate(betType, outcomes, true);

                logger.LogDebug("Generated to validate coupon:\n" + toValidateCoupon.GetDump());
                logger.LogDebug("Validate coupon was got from site:\n" + ToValidateCouponBySite["requestCoupon"].GetDump());

                Assert.IsTrue(JToken.DeepEquals(toValidateCoupon, ToValidateCouponBySite["requestCoupon"]));
            }
        }
        [TestMethod]
        public void Get_Success_PlaceBetCoupon_Tests()
        {
            using (logger.BeginScope(LoggerHelper.GetCaller()))
            {
                var placeBet
                    = helper.GenerateCouponToPlaceBet(outcomes, CheckedCouponBySite, betType, stake, ew);

                logger.LogDebug("Validate coupon:\n" + CheckedCouponBySite.GetDump());
                logger.LogDebug("Generated place bet coupon:\n" + placeBet.GetDump());
                logger.LogDebug("Place bet coupon was got from site:\n" + PlaceBetBySite.GetDump());

                Assert.IsTrue(JToken.DeepEquals(placeBet, PlaceBetBySite));
            }
        }

        /**** Data was generated by site ****/
        private JToken ToValidateCouponBySite
        {
            get
            {
                var json = "{\"requestCoupon\":{\"type\":\"RCT_SYSTEM\",\"odds\":[5000,4500,4000,3000,5000],\"outcomeIds\":[[2698640254],[2698640313],[2698640443],[2698640505],[2698640684]],\"selection\":[[],[],[],[],[]],\"betsPattern\":\"1111111111111111111111111111111\",\"isUserLoggedIn\":true}}";
                return JToken.Parse(json);
            }
        }

        private JToken CheckedCouponBySite
        {
            get
            {
                var json = "{\"responseCoupon\":{\"status\":200,\"requestCoupon\":{\"type\":\"RCT_SYSTEM\",\"outcomeIds\":[[2698640254],[2698640313],[2698640443],[2698640505],[2698640684]],\"odds\":[5000,4500,4000,3000,5000],\"betsPattern\":\"1111111111111111111111111111111\",\"allowOddsChange\":\"AOCT_NO\",\"selection\":[[],[],[],[],[]],\"suggestedRetailPunterCategory\":null}}}";
                return JToken.Parse(json)["responseCoupon"]["requestCoupon"];
            }
        }
        private JToken PlaceBetBySite
        {
            get
            {
                var json =

                  "{\"id\":1,\"trackingData\":{\"hasTeaser\":false,\"isBetBuilderCombination\":false,\"selectedOutcomes\":" +
                 "[{\"id\":2698640254,\"outcomeId\":2698640254,\"betofferId\":2198273474,\"eventId\":1006030695,\"approvedOdds\":5000,\"oddsApproved\":true,\"approvedEachWayFractionMilli\":200,\"approvedEachWayPlaceLimit\":3,\"eachWayFractionMilli\":200,\"eachWayPlaceLimit\":3,\"eachWayApproved\":true,\"isLiveBetoffer\":false,\"isPrematchBetoffer\":true,\"fromBetBuilder\":false,\"source\":\"Event List View\"}," +
                  "{\"id\":2698640313,\"outcomeId\":2698640313,\"betofferId\":2198273480,\"eventId\":1006030696,\"approvedOdds\":4500,\"oddsApproved\":true,\"approvedEachWayFractionMilli\":200,\"approvedEachWayPlaceLimit\":3,\"eachWayFractionMilli\":200,\"eachWayPlaceLimit\":3,\"eachWayApproved\":true,\"isLiveBetoffer\":false,\"isPrematchBetoffer\":true,\"fromBetBuilder\":false,\"source\":\"Event List View\"}," +
                  "{\"id\":2698640443,\"outcomeId\":2698640443,\"betofferId\":2198273492,\"eventId\":1006030698,\"approvedOdds\":4000,\"oddsApproved\":true,\"approvedEachWayFractionMilli\":250,\"approvedEachWayPlaceLimit\":3,\"eachWayFractionMilli\":250,\"eachWayPlaceLimit\":3,\"eachWayApproved\":true,\"isLiveBetoffer\":false,\"isPrematchBetoffer\":true,\"fromBetBuilder\":false,\"source\":\"Event List View\"}," +
                  "{\"id\":2698640505,\"outcomeId\":2698640505,\"betofferId\":2198273498,\"eventId\":1006030699,\"approvedOdds\":3000,\"oddsApproved\":true,\"approvedEachWayFractionMilli\":200,\"approvedEachWayPlaceLimit\":3,\"eachWayFractionMilli\":200,\"eachWayPlaceLimit\":3,\"eachWayApproved\":true,\"isLiveBetoffer\":false,\"isPrematchBetoffer\":true,\"fromBetBuilder\":false,\"source\":\"Event List View\"}," +
                  "{\"id\":2698640684,\"outcomeId\":2698640684,\"betofferId\":2198273516,\"eventId\":1006030702,\"approvedOdds\":5000,\"oddsApproved\":true,\"approvedEachWayFractionMilli\":200,\"approvedEachWayPlaceLimit\":3,\"eachWayFractionMilli\":200,\"eachWayPlaceLimit\":3,\"eachWayApproved\":true,\"isLiveBetoffer\":false,\"isPrematchBetoffer\":true,\"fromBetBuilder\":false,\"source\":\"Event List View\"}]}," +
                  "\"requestCoupon\":{\"allowOddsChange\":\"AOCT_NO\",\"odds\":[5000,4500,4000,3000,5000],\"stakes\":[10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10],\"outcomeIds\":[[2698640254],[2698640313],[2698640443],[2698640505],[2698640684]],\"type\":\"RCT_SYSTEM\",\"eachWayFraction\":[200,200,250,200,200],\"eachWayPlaceLimit\":[3,3,3,3,3],\"betsPattern\":\"0010111011111110111111111111111\",\"systemCombinations\":[{\"outcomeIds\":[2698640684],\"outcomePositions\":[5],\"patternIndex\":0},{\"outcomeIds\":[2698640505],\"outcomePositions\":[4],\"patternIndex\":1},{\"outcomeIds\":[2698640684,2698640505],\"outcomePositions\":[5,4],\"patternIndex\":2},{\"outcomeIds\":[2698640443],\"outcomePositions\":[3],\"patternIndex\":3},{\"outcomeIds\":[2698640684,2698640443],\"outcomePositions\":[5,3],\"patternIndex\":4},{\"outcomeIds\":[2698640505,2698640443],\"outcomePositions\":[4,3],\"patternIndex\":5},{\"outcomeIds\":[2698640684,2698640505,2698640443],\"outcomePositions\":[5,4,3],\"patternIndex\":6},{\"outcomeIds\":[2698640313],\"outcomePositions\":[2],\"patternIndex\":7},{\"outcomeIds\":[2698640684,2698640313],\"outcomePositions\":[5,2],\"patternIndex\":8},{\"outcomeIds\":[2698640505,2698640313],\"outcomePositions\":[4,2],\"patternIndex\":9},{\"outcomeIds\":[2698640684,2698640505,2698640313],\"outcomePositions\":[5,4,2],\"patternIndex\":10},{\"outcomeIds\":[2698640443,2698640313],\"outcomePositions\":[3,2],\"patternIndex\":11},{\"outcomeIds\":[2698640684,2698640443,2698640313],\"outcomePositions\":[5,3,2],\"patternIndex\":12},{\"outcomeIds\":[2698640505,2698640443,2698640313],\"outcomePositions\":[4,3,2],\"patternIndex\":13},{\"outcomeIds\":[2698640684,2698640505,2698640443,2698640313],\"outcomePositions\":[5,4,3,2],\"patternIndex\":14},{\"outcomeIds\":[2698640254],\"outcomePositions\":[1],\"patternIndex\":15},{\"outcomeIds\":[2698640684,2698640254],\"outcomePositions\":[5,1],\"patternIndex\":16},{\"outcomeIds\":[2698640505,2698640254],\"outcomePositions\":[4,1],\"patternIndex\":17},{\"outcomeIds\":[2698640684,2698640505,2698640254],\"outcomePositions\":[5,4,1],\"patternIndex\":18},{\"outcomeIds\":[2698640443,2698640254],\"outcomePositions\":[3,1],\"patternIndex\":19},{\"outcomeIds\":[2698640684,2698640443,2698640254],\"outcomePositions\":[5,3,1],\"patternIndex\":20},{\"outcomeIds\":[2698640505,2698640443,2698640254],\"outcomePositions\":[4,3,1],\"patternIndex\":21},{\"outcomeIds\":[2698640684,2698640505,2698640443,2698640254],\"outcomePositions\":[5,4,3,1],\"patternIndex\":22},{\"outcomeIds\":[2698640313,2698640254],\"outcomePositions\":[2,1],\"patternIndex\":23},{\"outcomeIds\":[2698640684,2698640313,2698640254],\"outcomePositions\":[5,2,1],\"patternIndex\":24},{\"outcomeIds\":[2698640505,2698640313,2698640254],\"outcomePositions\":[4,2,1],\"patternIndex\":25},{\"outcomeIds\":[2698640684,2698640505,2698640313,2698640254],\"outcomePositions\":[5,4,2,1],\"patternIndex\":26},{\"outcomeIds\":[2698640443,2698640313,2698640254],\"outcomePositions\":[3,2,1],\"patternIndex\":27},{\"outcomeIds\":[2698640684,2698640443,2698640313,2698640254],\"outcomePositions\":[5,3,2,1],\"patternIndex\":28},{\"outcomeIds\":[2698640505,2698640443,2698640313,2698640254],\"outcomePositions\":[4,3,2,1],\"patternIndex\":29},{\"outcomeIds\":[2698640684,2698640505,2698640443,2698640313,2698640254],\"outcomePositions\":[5,4,3,2,1],\"patternIndex\":30}],\"eachWay\":[true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true],\"selection\":[[],[],[],[],[]]}}";
                return JToken.Parse(json);
            }
        }
        /****************************************/
        private JArray InitOutcomes()
        {
            // horse and event info
            var json =
                "[{\"id\":2698640254,\"outcomeId\":2698640254,\"betofferId\":2198273474,\"eventId\":1006030695,\"approvedOdds\":5000,\"oddsApproved\":true,\"approvedEachWayFractionMilli\":200,\"approvedEachWayPlaceLimit\":3,\"eachWayFractionMilli\":200,\"eachWayPlaceLimit\":3,\"eachWayApproved\":true,\"isLiveBetoffer\":false,\"isPrematchBetoffer\":true,\"fromBetBuilder\":false,\"source\":\"Event List View\"}," +
                "{\"id\":2698640313,\"outcomeId\":2698640313,\"betofferId\":2198273480,\"eventId\":1006030696,\"approvedOdds\":4500,\"oddsApproved\":true,\"approvedEachWayFractionMilli\":200,\"approvedEachWayPlaceLimit\":3,\"eachWayFractionMilli\":200,\"eachWayPlaceLimit\":3,\"eachWayApproved\":true,\"isLiveBetoffer\":false,\"isPrematchBetoffer\":true,\"fromBetBuilder\":false,\"source\":\"Event List View\"}," +
                "{\"id\":2698640443,\"outcomeId\":2698640443,\"betofferId\":2198273492,\"eventId\":1006030698,\"approvedOdds\":4000,\"oddsApproved\":true,\"approvedEachWayFractionMilli\":250,\"approvedEachWayPlaceLimit\":3,\"eachWayFractionMilli\":250,\"eachWayPlaceLimit\":3,\"eachWayApproved\":true,\"isLiveBetoffer\":false,\"isPrematchBetoffer\":true,\"fromBetBuilder\":false,\"source\":\"Event List View\"}," +
                "{\"id\":2698640505,\"outcomeId\":2698640505,\"betofferId\":2198273498,\"eventId\":1006030699,\"approvedOdds\":3000,\"oddsApproved\":true,\"approvedEachWayFractionMilli\":200,\"approvedEachWayPlaceLimit\":3,\"eachWayFractionMilli\":200,\"eachWayPlaceLimit\":3,\"eachWayApproved\":true,\"isLiveBetoffer\":false,\"isPrematchBetoffer\":true,\"fromBetBuilder\":false,\"source\":\"Event List View\"}," +
                "{\"id\":2698640684,\"outcomeId\":2698640684,\"betofferId\":2198273516,\"eventId\":1006030702,\"approvedOdds\":5000,\"oddsApproved\":true,\"approvedEachWayFractionMilli\":200,\"approvedEachWayPlaceLimit\":3,\"eachWayFractionMilli\":200,\"eachWayPlaceLimit\":3,\"eachWayApproved\":true,\"isLiveBetoffer\":false,\"isPrematchBetoffer\":true,\"fromBetBuilder\":false,\"source\":\"Event List View\"}]";


            return JToken.Parse(json) as JArray;
        }

        private ILogger InitLogger()
        {
            AppLogger.LoggerFactory.AddSmartInspect(new SmartInspectConfiguration
            {
                AppName = "Tester",
                Enabled = true,
                Level = LogLevel.Trace,
                DefaultLevel = LogLevel.Trace,
                Connections = @"pipe(reconnect=""true"", reconnect.interval=""5"", async.enabled=""true"", async.throttle=""false"")"
            });
            return AppLogger.CreateLogger("Main");
        }
    }
}
